export const GET_ADMIN_REQUEST="GET_ADMIN_REQUEST"
export const GET_ADMIN_SUCCESS="GET_ADMIN_SUCCESS"
export const GET_ADMIN_FAILURE="GET_ADMIN_FAILURE"

export const GET_USERS_REQUEST="GET_USERS_REQUEST"
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAILURE="GET_USERS_FAILURE"