export const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE=" ADD_TO_CART_FAILURE"

export const FETCH_CART_PRODUCT_REQUEST="FETCH_CART_PRODUCT_REQUEST"
export const FETCH_CART_PRODUCT_SUCCESS="FETCH_CART_PRODUCT_SUCCESS"
export const FETCH_CART_PRODUCT_FAILURE="FETCH_CART_PRODUCT_FAILURE"

export const REMOVE_TO_CART_REQUEST="REMOVE_TO_CART_REQUEST"
export const REMOVE_TO_CART_SUCCESS="REMOVE_TO_CART_SUCCESS"
export const REMOVE_TO_CART_FAILURE=" REMOVE_TO_CART_FAILURE"


export const ADD_TO_WISHLIST_REQUEST="ADD_TO_WISHLIST_REQUEST"
export const ADD_TO_WISHLIST_SUCCESS="ADD_TO_WISHLIST_SUCCESS"
export const ADD_TO_WISHLIST_FAILURE=" ADD_TO_WISHLIST_FAILURE"

export const FETCH_WISHLIST_PRODUCT_REQUEST="FETCH_CART_WISHLIST_REQUEST"
export const FETCH_WISHLIST_PRODUCT_SUCCESS="FETCH_CART_WISHLIST_SUCCESS"
export const FETCH_WISHLIST_PRODUCT_FAILURE="FETCH_CART_WISHLIST_FAILURE"


export const INCREASE_QUANTITY_REQUEST="INCREASE_QUANTITY_REQUEST"
export const INCREASE_QUANTITY_SUCCESS="INCREASE_QUANTITY_SUCCESS"
export const INCREASE_QUANTITY_FAILURE="INCREASE_QUANTITY_FAILURE"

export const DECREASE_QUANTITY_REQUEST="DECREASE_QUANTITY_REQUEST"
export const DECREASE_QUANTITY_SUCCESS="DECREASE_QUANTITY_SUCCESS"
export const DECREASE_QUANTITY_FAILURE="DECREASE_QUANTITY_FAILURE"









