export const FETCH_PRODUCT_REQUEST="FETCH_PRODUCT_REQUEST"
export const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_FAILURE="FETCH_PRODUCT_FAILURE"

// constants/product.js
export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAILURE = "SEARCH_PRODUCT_FAILURE";
