export const REGISTER_USER_REQUEST = " REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = " REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = " REGISTER_USER_FAILURE"

export const OTP_VERIFICATION_REQUEST = "OTP_VERIFICATION_REQUEST"
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS"
export const OTP_VERIFICATION_FAILURE = "OTP_VERIFICATION_FAILURE"


export const NEW_OTP_GENERATE_REQUEST = " NEW_OTP_GENERATE_REQUEST"
export const NEW_OTP_GENERATE_SUCCESS = " NEW_OTP_GENERATE_SUCCESS"
export const NEW_OTP_GENERATE_FAILURE = " NEW_OTP_GENERATE_FALIURE"

export const LOGIN_USER_REQUEST = " LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = " LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"


export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST'
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE'

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE'

export const UPDATE_PASSWORD_REQUEST =" UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS =" UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAILURE =" UPDATE_PASSWORD_FAILURE"


export const RESET_USER_FLAGS = ' RESET_USER_FLAGS'


export const LOGOUT_USER_REQUEST=" LOGOUT_USER_REQUEST"
export const LOGOUT_USER_SUCCESS=" LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAILURE=" LOGOUT_USER_FAILURE"

export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAILURE="GET_USER_FAILURE"

export const ADD_ADDRESS_REQUEST="ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS="ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAILURE="ADD_ADDRESS_FAILURE"


export const GET_ADDRESS_REQUEST ="GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS =" GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAILURE ="GET_ADDRESS_FAILURE"

export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILURE="PLACE_ORDER_FAILURE"


